server:
  port: 8350

# spring的一些配置
spring:
  application:
    name: message

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whiteholecloud-message?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: WhiteHoleCloud
    password: 865989840

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: message

#Netty的一些配置
netty:
  boss: 1
  worker: 4
  timeout: 6000
  port: 9000
  host: 127.0.0.1
