

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: gateway
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #这里先做一个基本的服务转发
        - id: activiy8000
          uri: lb://activiy
          predicates:
            - Path=/activiy/**
          filters:
            - StripPrefix=1

        - id: blog8050
          uri: lb://blog
          predicates:
            - Path=/blog/**
          filters:
            #- 转发做拼接，去掉provide后缀，uri/** 而不是 uri/provide/**
            - StripPrefix=1
        # 与之对于的还有 PrefixPath=/Huterox
        #  当访问 http://localhost:8762/aaa，加上前缀就变成 http://localhost:8762/Huterox/aaa

        - id: community8100
          uri: lb://community
          predicates:
            - Path=/community/**
          filter:
            - StripPrefix=1

        - id: hole8150
          uri: lb://hole
          predicates:
            - Path=/hole/**
          filter:
            - StripPrefix=1


        - id: quiz8200
          uri: lb://quiz
          predicates:
            - Path=/quiz/**
          filter:
            - StripPrefix=1

        - id: user8250
          uri: lb://user
          predicates:
            - Path=/user/**
          filter:
            - StripPrefix=1


        - id: admin_route
          uri: lb://renren-fast  # 网关负载均衡的发送到renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}  #实现路径重写

  ## 所有前端项目带  /api
  ## http://localhost:88/api/captcha.jpg
  ## http://localhost:8080/renren-fast/captcha.jpg



  application:
    name: gateway




server:
  port: 88


